version: '3.8'

services:
  # LOKI: Log Aggregation System
  loki:
    image: grafana/loki:latest
    container_name: ghost-loki
    volumes:
      # Mount the loki-config
      - ./loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  # PROMTAIL: Collector - Ships logs to Loki
  promtail:
    image: grafana/promtail:latest
    container_name: ghost-promtail
    volumes:
      # Mount the promtail-config
      - ./promtail-config.yml:/etc/promtail/config.yml
      # Mount the physical ghost logs directory (Active logs only)
      - /home/praveen/ghost/log_rotating/active:/var/log/ghost/active:ro
    command: -config.file=/etc/promtail/config.yml
    restart: always
    depends_on:
      - loki

  # GRAFANA: Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: ghost-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default pass
    restart: always
    depends_on:
      - loki

volumes:
  grafana-data:
